# Site settings
title: Jacob D Lewis
email: jacobdlewis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My journey as an up-and-coming web developer. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
